POST http://localhost:3000/available-car HTTP/1.1
Content-Type: application/json

{
  "car_category": {
    "id": "8e33220d-c8e7-4182-a4c9-82fd1e0c47ec",
    "name": "Coupe",
    "carIds": [
      "7710cef9-f9ae-4b35-9f87-7f327c8d4e64",
      "5ec0a6de-42f8-447a-96bc-46065edb878d",
      "3f736619-fc8f-49a6-92e1-eb9f24c4d6b0"
    ],
    "price": "47.46"
  }
}

###
POST http://localhost:3000/register_renting HTTP/1.1
Content-Type: application/json

{
  "car_category": {
    "id": "8e33220d-c8e7-4182-a4c9-82fd1e0c47ec",
    "name": "Coupe",
    "carIds": [
      "7710cef9-f9ae-4b35-9f87-7f327c8d4e64",
      "5ec0a6de-42f8-447a-96bc-46065edb878d",
      "3f736619-fc8f-49a6-92e1-eb9f24c4d6b0"
    ],
    "price": "47.46"
  },
  "customer": {
  "id": "e5a06ca2-b307-491e-85ff-c462a7b0dd2d",
  "name": "Cody Wiza",
  "age": "43"
  },
  "days": 5
}